### ISSUE TITLE
Error message

### ISSUE THREAD

**Issue by giuliaguidi** [epolevikov/Asgan#2]
Hi,

If I compare a file against itself (dumb test), Asgan completes correctly. But if I compare two different files, I get this error:

```
Parsing assembly graphs..
Extracting sequences..
Aligning sequences..
Traceback (most recent call last):
  File "asgan.py", line 10, in <module>
    main()
  File "/Users/gguidi/Desktop/projects/Asgan/src/main.py", line 49, in main
    processed_hits = ht.process_raw_hits(filtered_hits)
  File "/Users/gguidi/Desktop/projects/Asgan/src/hits.py", line 51, in process_raw_hits
    united_hits = unite_processed_hits(processed_hits)
  File "/Users/gguidi/Desktop/projects/Asgan/src/hits.py", line 120, in unite_processed_hits
    curr_hit = processed_hits[0]
IndexError: list index out of range
```

I used the following command and here's a [link](https://drive.google.com/drive/folders/1cey2VsHjt2URKF40NtO97LoUyMhsgBG2?usp=sharing) to these small files:

```
python asgan.py --input-query=../assembly1.gfa --input-target=../assembly2.gfa --out-dir=test
```

The error occurs when comparing _assembly1_ to either _assembly2_ or _assembly3_. If I run with _assembly1_ against itself (and same for _assembly2_ and _assembly3_), it works. Please, let me know if there's something trivial I'm missing.

Thanks,
Giulia

**Comment by epolevikov** [comment]
Hi Giulia,

_Asgan_ utilizes _minimap2_ to find an alignment between two assemblies. By default, _minimap2_ is used with the "asm10" preset. If two assemblies have high sequence divergence (>10%), _minimap2_ will not find alignments between them. Most likely, your error occurred because of the assemblies diverge much.

For highly diverge species, you may use either "map-pb" or "map-ont" preset, both of them work fine for your datasets. I have added an argument "--minimap-preset" that you may use to change the default preset. Try to run it as follows:
```
python asgan.py --input-query=.. --input-target=.. --minimap-preset=map-ont --out-dir=..
``` 

Sorry for the lack of documentation. For now, I don't have enough time to maintain the project. If you have any questions, feel free to ask me here.

Best,
Evgeny

**Comment by epolevikov** [comment]
Closing the issue. See the updated documentation. Feel free to reopen if you have any questions or the issue remains.

**Comment by lucaspr98** [comment]
I'm having the same problem, even using the --minimap-preset flag I got the same error. 

I tried Asgan on the following GFAs from the gfalint examples and got the same error as @giuliaguidi 

https://github.com/sjackman/gfalint/tree/master/examples

Thanks,
Lucas.

**Comment by epolevikov** [comment]
Hi @lucaspr98

Would you please post the complete command you use to run Asgan?

Thanks,
Eugene

**Comment by lucaspr98** [comment]
Of course, I ran the following command:

python -m asgan --input-query=../gfalint/examples/big1.gfa --input-target=../gfalint/examples/big2.gfa --minimap-preset=sr --out-dir=big1-vs-big2

I also tried --minimap-preset=map-pb and  --minimap-preset=map-ontas you put in the documentation, but in all cases I got the following error:

Parsing assembly graphs..
Extracting sequences..
Aligning sequences..
Traceback (most recent call last):
  File "/usr/lib/python2.7/runpy.py", line 174, in _run_module_as_main
    "__main__", fname, loader, pkg_name)
  File "/usr/lib/python2.7/runpy.py", line 72, in _run_code
    exec code in run_globals
  File "/mnt/data/projects/lucas/Asgan/asgan/__main__.py", line 10, in <module>
    main()
  File "asgan/main.py", line 50, in main
    processed_hits = ht.process_raw_hits(filtered_hits)
  File "asgan/hits.py", line 51, in process_raw_hits
    united_hits = unite_processed_hits(processed_hits)
  File "asgan/hits.py", line 120, in unite_processed_hits
    curr_hit = processed_hits[0]
IndexError: list index out of range

I also tried with sample1 and sample2 from gfalint examples, but always the same error.

**Comment by epolevikov** [comment]
This error occurs because `minimap2` cannot find any similarities between the sequences in the specified files. For the `big1.gfa` and `big2.gfa` files it's quite expected since the files don't contain any sequences at all. The `sample1.gfa` and `sample2.gfa` contain some sequences, but I guess they are too short, so `minimap2` cannot find any alignment as well.

What did you expect to see as output for these sequences?

**Comment by lucaspr98** [comment]
Actually I'm interested in running Asgan for a set of Vibrios genomes, I ran a few gfa files obtained from distinct assemblers, but all tests gave me this same error. Therefore my first thought was that there was something wrong with the gfa files, so I was trying to run Asgan with some small tests which I was sure that the gfa were ok.

In this link I have two Vibrios genomes in fastq format and some gfa obtained from distinct assemblers (Megahit, abyss, bcalm):

https://drive.google.com/drive/folders/1k3GJK9kTm-pme_gSz52DHQPv3BYDk1BX?usp=sharing

Thank you very much for your attention.

**Comment by epolevikov** [comment]
I don't have access to your google drive folder.

I guess the issue might be the same: your gfa files are most likely to miss the sequences while Asgan expects the sequence to be stored inside the gfa files. So before you run the tool, make sure that your gfa files contain sequences themselfes (not only alignment results). You might find some examples of how gfa files should look like in the `test` folder, and also run Asgan for these files.

If your sequences are stored in separated files (fasta of fastq e.g), you might try to use helper scripts to convert those files to gfa ([fasta2gfa.py](https://github.com/epolevikov/Asgan/blob/master/helpers/fasta2gfa.py)) or add sequences to a gfa file ([gfa_add_sequences.py](https://github.com/epolevikov/Asgan/blob/master/helpers/gfa_add_sequences.py)).

**Comment by lucaspr98** [comment]
Okay, I guess my gfa files didn't have the sequences. Thank you very much for the feedback, I'll try to run it again!

**Comment by epolevikov** [comment]
You are welcome. Let me know if you have any other questions.

**Comment by lucaspr98** [comment]
Hello again! 

I tried again, now with the sequences in the gfa files (I guess), and with the files sorted as in the test examples (H->S->L->P). I'm still getting the same errors, do you think the sequences are to short and this is causing the error? Here are the gfa files (the extension is in .txt so I could put them here in this issue comment)

[photobacterium_angustum_64_filled_sorted.txt](https://github.com/epolevikov/Asgan/files/7703754/photobacterium_angustum_64_filled_sorted.txt)
[aliivibrio_fischeri_64_filled_sorted.txt](https://github.com/epolevikov/Asgan/files/7703761/aliivibrio_fischeri_64_filled_sorted.txt)

If you have any trouble opening this files, I also made the drive  link (https://github.com/epolevikov/Asgan/issues/2#issuecomment-980312064) in this issue public.

Thank you very much again, and sorry for bothering.

**Comment by epolevikov** [comment]
Hi

Another possible reason why this error might happen is that the sequences don't have similar regions. In that case, minimap2 cannot find any alignments, and this causes the error.

Are you sure that these sequences contain similar regions? You would try to run minimap2 first for these sequences and see the results. If minimap2 cannot find anything, there is not much Asgan can do.
